Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyMVC.Models
{
    public class Enrollment
    {
       public int Id { get; set; }

       public string Semester { get; set; }

       public int Year { get; set; }

       public int? Grade { get; set; }

       public string SeminalUrl { get; set; }

       [StringLength(255)]
       public string ProjectUrl { get; set; }

       public int? ExamPoints { get; set; }
       public int? SeminalPoints { get; set; }
       public int? ProjectPoints { get; set; }
       public int? AdditionalPoints { get; set; }

       [DataType(DataType.Date)]
       public DateTime? FinishDate { get; set; }

       public int CourseId { get; set; }
       public Course Course { get; set; }
       public int StudentId { get; set; }
       public Student Student { get; set; }
    }
}

ViewModels/CourseStudentViewModel.cs
/*using FacultyMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyMVC.ViewModels
{
    public class CourseStudentViewModel
    {
        public Course Course { get; set; }
        public IEnumerable<int> SelectedStudents { get; set; }
        public IEnumerable<SelectListItem> StudentsList { get; set; }
    }
}
*/



//FAZA1

ViewModels/EnrollmentViewModel.cs
using FacultyMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyMVC.ViewModels
{
    public class EnrollmentViewModel
    {
        public Enrollment NewEnrollment { get; set; }
        public IEnumerable<int> SelectedStudents { get; set; }
        public IEnumerable<SelectListItem> StudentsList { get; set; }
    }
}

Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FacultyMVC.Data;
using FacultyMVC.Models;
using FacultyMVC.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FacultyMVC.Controllers
{
    
    public class EnrollmentsController : Controller
    {
        private readonly FacultyMVCContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private UserManager<AppUser> userManager;

        public EnrollmentsController(FacultyMVCContext context, IWebHostEnvironment webHostEnvironment, UserManager<AppUser> userMan)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            userManager = userMan;
        }

        // GET: Enrollments
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string enrollmentCourse, int enrollmentYear, string enrollmentSemester) 
        {
            IQueryable<Enrollment> enrollments = _context.Enrollment.AsQueryable();
            IQueryable<int> yearQuery = _context.Enrollment.OrderBy(m => m.Year).Select(m => m.Year).Distinct(); 
            IQueryable<string> semesterQuery = _context.Enrollment.Where(m => m.Semester != null).OrderBy(m => m.Semester).Select(m => m.Semester).Distinct(); //ama ne mi gi zema distinct

            if (!string.IsNullOrEmpty(enrollmentCourse))
            {
                enrollments = enrollments.Where(s => s.Course.Title.ToLower().Contains(enrollmentCourse.ToLower()));
            }
            if (enrollmentYear != 0)
            {
                enrollments = enrollments.Where(x => x.Year == enrollmentYear);
            }
            if (!string.IsNullOrEmpty(enrollmentSemester))
            {
                enrollments = enrollments.Where(s => s.Semester.Equals(enrollmentSemester) );
            }

            var vm = new EnrollmentFilterViewModel
            {
                Years = new SelectList(await yearQuery.ToListAsync()), 
                Semesters = new SelectList(await semesterQuery.ToListAsync()),
                Enrollments = await enrollments.OrderBy(e=>e.Course.Title).Include(s => s.Course).Include(s=>s.Student).ToListAsync()
            };
            return View(vm); 
        }

        // GET: Enrollments/CourseStudents/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> CourseStudents(int? id, int enrollmentYear)
        {
            if (id == null)
            {
                return NotFound();
            }

            IQueryable<Enrollment> enrollments = _context.Enrollment.Where(e => e.CourseId == id);
            enrollments = enrollments.Include(e => e.Course).Include(e => e.Student).OrderBy(e=>e.Student.Index).OrderBy(e=>e.Student.Index);
            
            if(enrollments != null)
            {
                var anyenrollment = enrollments.First();
                AppUser loggedUser = await userManager.GetUserAsync(User);
                if ((loggedUser.TeacherId != anyenrollment.Course.FirstTeacherId) && (loggedUser.TeacherId != anyenrollment.Course.SecondTeacherId))
                {
                    return RedirectToAction("AccessDenied", "Account", null);
                }
            }

            if (enrollmentYear != 0)
            {
                enrollments = enrollments.Where(x => x.Year == enrollmentYear);
            }
            else
            {
                //po default se prikazuvat studentite zapisani vo poslednata godina
                enrollments = enrollments.Where(x => x.Year == DateTime.Now.Year);
            }

            EnrollmentFilterViewModel vm = new EnrollmentFilterViewModel
            {
                Enrollments = await enrollments.ToListAsync()
            };

            ViewData["CourseName"] = _context.Course.Where(c => c.Id == id).Select(c => c.Title).FirstOrDefault();
            return View(vm);
        }

        // GET: Enrollments/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title");
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FirstName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate,CourseId,StudentId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FirstName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5 
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Enrollment enrollment = await _context.Enrollment.Include(e => e.Course).Where(e => e.Id == id).FirstOrDefaultAsync();
            if (enrollment == null)
            {
                return NotFound();
            }
           

            AppUser loggedUser = await userManager.GetUserAsync(User);
            if ((loggedUser.TeacherId != enrollment.Course.FirstTeacherId) && (loggedUser.TeacherId != enrollment.Course.SecondTeacherId))
            {
                return RedirectToAction("AccessDenied", "Account", null);
            }

            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);
            ViewData["StudentName"] = _context.Student.Where(s => s.Id == enrollment.StudentId).Select(s => s.FullName).FirstOrDefault();
            ViewData["CourseName"] = _context.Course.Where(s => s.Id == enrollment.CourseId).Select(s => s.Title).FirstOrDefault();
            return View(enrollment);
        }

        // GET: Enrollments/EditByAdmin/5 
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditByAdmin(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }

            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);
            ViewData["StudentName"] = _context.Student.Where(s => s.Id == enrollment.StudentId).Select(s => s.FullName).FirstOrDefault();
            ViewData["CourseName"] = _context.Course.Where(s => s.Id == enrollment.CourseId).Select(s => s.Title).FirstOrDefault();
            return View(enrollment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Teacher")]
        public async Task<IActionResult> Edit(int id, string pom, [Bind("Id,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate,CourseId,StudentId")] Enrollment enrollment)
        {
            if (id != enrollment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (pom.Equals("admin"))
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("CourseStudents", new { id = enrollment.CourseId });
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);

            if (pom.Equals("admin"))
            {
                return View("EditByAdmin", enrollment);
            }
            else {
                return View(enrollment); }
        }

        // GET: Enrollments/Details/5
        [Authorize(Roles = "Student")] 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (enrollment == null)
            {
                return NotFound();
            }

            AppUser loggedUser = await userManager.GetUserAsync(User);
            if (loggedUser.StudentId != enrollment.StudentId)
            {
                return RedirectToAction("AccessDenied", "Account", null);
            }

            return View(enrollment);
        }

Views/Enrollments/CourseStudents.cshtml
@model FacultyMVC.ViewModels.EnrollmentFilterViewModel


<h2>Enrolled students for @ViewData["CourseName"] </h2>
<br />

<form asp-controller="Enrollments" asp-action="CourseStudents" method="get">
    <p>
        @Html.DropDownListFor(m => m.EnrollmentYear, Enumerable.Range(2010, DateTime.Now.Year - 2010 + 1).Reverse().Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString()}))

        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Student.Index)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Student.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].SeminalUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ProjectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ExamPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].SeminalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ProjectPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].AdditionalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].FinishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.Index)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Semester)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td>
                    @if (item.SeminalUrl != null)
                    {
                        <a href="@Url.Content("~/seminalFiles/" + item.SeminalUrl)">View</a>
                        @Html.ActionLink("Download", "DownloadFile", new { filename = item.SeminalUrl })
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectUrl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamPoints)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SeminalPoints)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectPoints)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdditionalPoints)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FinishDate)
                </td>
                <td>
                    @if (item.FinishDate == null)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>


<!-- Teachers/GetCourses/TeacherId no za eden enrollment ima dva profesori pa ne moze da se znae koe kje e TeacherId
<div>
    <a asp-controller="Teachers" asp-action="GetCourses" asp-route-id=" ">Back to Courses</a>
</div>
-->

Views/Enrollments/Create.cshtml
@model FacultyMVC.Models.Enrollment

<h1>Create</h1>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalUrl" class="control-label"></label>
                <input asp-for="SeminalUrl" class="form-control" />
                <span asp-validation-for="SeminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectUrl" class="control-label"></label>
                <input asp-for="ProjectUrl" class="form-control" />
                <span asp-validation-for="ProjectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamPoints" class="control-label"></label>
                <input asp-for="ExamPoints" class="form-control" />
                <span asp-validation-for="ExamPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalPoints" class="control-label"></label>
                <input asp-for="SeminalPoints" class="form-control" />
                <span asp-validation-for="SeminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPoints" class="control-label"></label>
                <input asp-for="ProjectPoints" class="form-control" />
                <span asp-validation-for="ProjectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalPoints" class="control-label"></label>
                <input asp-for="AdditionalPoints" class="form-control" />
                <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Enrollments/Delete.cshtml
@model FacultyMVC.Models.Enrollment

<h1>Delete</h1>

<h3>Are you sure you want to delete this enrollment?</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Enrollments/Details.cshtml
@model FacultyMVC.Models.Enrollment

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class="col-sm-10">
            @if (Model.SeminalUrl != null)
            {
                <a href="@Url.Content("~/seminalFiles/" + Model.SeminalUrl)">@Model.SeminalUrl</a>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
    </dl>

    <div>
        <a asp-controller="Students" asp-action="MyCourses" asp-route-id="@Model.StudentId">Back to List</a>
    </div>
        

</div>

Views/Enrollments/Index.cshtml
@model FacultyMVC.ViewModels.EnrollmentFilterViewModel

<h2>Enrollments</h2>

<form asp-controller="Enrollments" asp-action="Index" method="get">
    <p>
        Course: <input type="text" asp-for="EnrollmentCourse" />
        <select asp-for="EnrollmentSemester" asp-items="Model.Semesters">
            <option value="">SEMESTER</option>
        </select>
        <select asp-for="EnrollmentYear" asp-items="Model.Years.Reverse()">
            <option value="">YEAR</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Student.Index)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].FinishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Enrollments)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.Index)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                |<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|
                <a asp-action="EditByAdmin" asp-route-id="@item.Id">Edit</a>|
            </td>
        </tr>
        }
    </tbody>
</table>