Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyMVC.Models
{
    public class Teacher
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [StringLength(50)]
        public string Degree { get; set; }

        [StringLength(25)]
        public string AcademicRank { get; set; }

        [StringLength(10)]
        public string OfficeNumber { get; set; }

        [DataType(DataType.Date)]
        public DateTime? HireDate { get; set; }

        public string ProfilePicture { get; set; }

        public string FullName {
            //get { return string.Format("{0}, {1}", FirstName, LastName);}
            get { return FirstName + " " + LastName; }
            
        }

        public ICollection<Course> Courses_first { get; set; }

        public ICollection<Course> Courses_second { get; set; }
    }
}

Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FacultyMVC.Data;
using FacultyMVC.Models;
using FacultyMVC.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FacultyMVC.Controllers
{
    
    public class TeachersController : Controller
    {
        private UserManager<AppUser> userManager;
        private readonly FacultyMVCContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TeachersController(FacultyMVCContext context, IWebHostEnvironment webHostEnvironment, UserManager<AppUser> usrMgr)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            userManager = usrMgr;
        }


        // GET: Teachers
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string teacherAcademicRank, string teacherDegree, string searchString)
        {

            //IQueryable<Teacher> teachers = _context.Teacher.AsQueryable();  
            IEnumerable<Teacher> teachers = _context.Teacher;
            IQueryable<string> rankQuery = _context.Teacher.Where(m=>m.AcademicRank != null).OrderBy(m => m.AcademicRank).Select(m => m.AcademicRank).Distinct();
            IQueryable<string> degreeQuery = _context.Teacher.Where(m=>m.Degree != null).OrderBy(m => m.Degree).Select(m => m.Degree).Distinct();

            if (!string.IsNullOrEmpty(teacherAcademicRank))
            {
                teachers = teachers.Where(x => x.AcademicRank == teacherAcademicRank);
            }
            if (!string.IsNullOrEmpty(teacherDegree))
            {
                teachers = teachers.Where(x => x.Degree == teacherDegree);
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                teachers = teachers.ToList().Where(s => s.FullName.ToLower().Contains(searchString.ToLower()));
                //teachers = teachers.Where(s => s.FullName.Contains(searchString));  //ne raboti
            }


            var teacherViewModel = new TeacherFilterViewModel
            {
                Ranges = new SelectList(await rankQuery.ToListAsync()),
                Degrees = new SelectList(await degreeQuery.ToListAsync()),
                Teachers = teachers.ToList()
            };

            return View(teacherViewModel);
        }

        // GET: Teachers/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeacherFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(model);

                Teacher teacher = new Teacher
                {
                    
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Degree = model.Degree,
                    AcademicRank = model.AcademicRank,
                    OfficeNumber = model.OfficeNumber,
                    HireDate = model.HireDate,
                    ProfilePicture = uniqueFileName,
                    Courses_first = model.Courses_first,
                    Courses_second = model.Courses_second
                };

                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private string UploadedFile(TeacherFormViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfilePicture != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.ProfilePicture.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfilePicture.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Teachers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }

            TeacherFormViewModel vm = new TeacherFormViewModel
            {
                Id = teacher.Id,
                FirstName = teacher.FirstName,
                LastName = teacher.LastName,
                Degree = teacher.Degree,
                AcademicRank = teacher.AcademicRank,
                OfficeNumber = teacher.OfficeNumber,
                HireDate = teacher.HireDate,
                Courses_first = teacher.Courses_first,
                Courses_second = teacher.Courses_second
            };

            return View(vm);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, TeacherFormViewModel vm)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string uniqueFileName = UploadedFile(vm);

                    Teacher teacher = new Teacher
                    {
                        Id = vm.Id,
                        FirstName = vm.FirstName,
                        LastName = vm.LastName,
                        ProfilePicture = uniqueFileName,
                        Degree = vm.Degree,
                        AcademicRank = vm.AcademicRank,
                        OfficeNumber = vm.OfficeNumber,
                        HireDate = vm.HireDate,
                        Courses_first = vm.Courses_first,
                        Courses_second = vm.Courses_second
                    };

                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(vm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vm);
        }

        // GET: Teachers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);

            //delete image file from the folder
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "images", teacher.ProfilePicture);
            FileInfo file = new FileInfo(path);
            if (file.Exists)//check file exsit or not
            {
                file.Delete();
            }

            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }

        // GET: Teachers/GetCourses/2
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> GetCourses(int id)
        {
            AppUser loggedUser = await userManager.GetUserAsync(User);
            if (loggedUser.TeacherId != id)
            {
                return RedirectToAction("AccessDenied", "Account", null);
            }

            var courses = _context.Course.Where(c=>c.FirstTeacherId == id || c.SecondTeacherId == id);
            courses = courses.Include(t=>t.FirstTeacher).Include(t=>t.SecondTeacher);

            ViewData["TeacherId"] = id;

Views/Teachers/Create.cshtml
@model FacultyMVC.ViewModels.TeacherFormViewModel

<h1>Create</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for=" ProfilePicture" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for=" ProfilePicture" type="file" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose image file</label>
                </div>
                <span asp-validation-for=" ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

Views/Teachers/Delete.cshtml
@model FacultyMVC.Models.Teacher

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Teachers/Details.cshtml
@model FacultyMVC.Models.Teacher

<h1>Details</h1>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Teachers/Edit.cshtml
@model FacultyMVC.ViewModels.TeacherFormViewModel

<h1>Edit</h1>
<h4>Teacher</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for=" ProfilePicture" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for=" ProfilePicture" type="file" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose image file</label>
                </div>
                <span asp-validation-for=" ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

Views/Teachers/GetCourses.cshtml
@model IEnumerable<FacultyMVC.Models.Course>

<h4>@ViewData["TeacherAcademicRank"] @ViewData["TeacherName"]'s courses </h4>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstTeacher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondTeacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Credits)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Semester)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Programme)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EducationLevel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstTeacher.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecondTeacher.FullName)
                </td>
                <td>
                   <a asp-controller="Enrollments" asp-action="CourseStudents" asp-route-id="@item.Id">View Students</a> 
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Teachers/Index.cshtml
@model FacultyMVC.ViewModels.TeacherFilterViewModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<AppUser> UserManager

<h2>Teachers</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Teachers" asp-action="Index" method="get">
    <p>
        <select asp-for="TeacherAcademicRank" asp-items="Model.Ranges">
            <option value="">ACADEMIC RANK</option>
        </select>
        <select asp-for="TeacherDegree" asp-items="Model.Degrees">
            <option value="">DEGREE</option>
        </select>
        Full Name: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].AcademicRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].OfficeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].HireDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Teachers)
        {
            <tr>
                <td>
                    @{ if (item.ProfilePicture != null)
                        {
                            <img src="~/images/@item.ProfilePicture"
                                 class="rounded-circle"
                                 height="40" width="40"
                                 asp-append-version="true" />}
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Degree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AcademicRank)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OfficeNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HireDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |

                    @{
                        IQueryable<AppUser> users = UserManager.Users;
                        IQueryable<int> ids = users.Select(u => u.TeacherId).Distinct();
                        if (ids.Contains(item.Id))
                        {
                            AppUser teacher = users.Where(u => u.TeacherId == item.Id).First();
                            <a asp-controller="Admin" asp-action="Update" asp-route-id="@teacher.Id">Profile</a>
                        }
                        else
                        {
                            <a asp-controller="Admin" asp-action="Create" asp-route-teacherid="@item.Id">Profile</a>
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>